name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: SSH Setting
      env:
        TOKEN: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p /home/runner/.ssh/
        echo -e "$TOKEN" > /home/runner/.ssh/id_ed25519
        chmod 600 /home/runner/.ssh/id_ed25519
    - name: SSH check
      run: ssh git@github.com
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --verbose
